### ISSUE TITLE
[FIX] Unable to login in the preview environment

### ISSUE THREAD

**Issue by ux-git** [sws2apps/organized-app#1268]
**Describe the bug**
Can't login with Google (error) nor with email (doesn't show a dummy link)

**Screenshots**
<img width="636" alt="Screenshot 2024-03-18 at 19 11 44" src="https://github.com/sws2apps/organized-app/assets/80993061/f72dac55-ca88-4f2f-92fc-054c18963e55">
<img width="636" alt="Screenshot 2024-03-18 at 19 11 53" src="https://github.com/sws2apps/organized-app/assets/80993061/5f040a8c-882f-401e-82ed-7c21f9b6267f">

**Additional context**
The latest 10m-old version

**Comment by rhahao** [comment]
@ux-git: very sorry for this. I’ve added the new preview url to the list of approved domains now. You can try again after few minutes.

**Comment by ux-git** [comment]
@rhahao thanks, now it works!
