### ISSUE TITLE
[FEAT] Open page in a new tab when holding Ctrl/Cmd key

### ISSUE THREAD

**Issue by ux-git** [sws2apps/organized-app#1275]
**Is your feature request related to a problem? Please describe.**
When user tries to open a page in a new tab with a known "hold the Ctrl" approach, it still leaves the page and open the page in the current tab.

**Describe the solution you'd like**
Open page in the new tab when clicking while holding Ctrl/Cmd key

**Describe alternatives you've considered**
Open the app from bookmarks in a new tab and then go and open the second desired page. 

**Additional context**
Not sure how in should behave in mobile PWA-mode (perhaps disable this feature there), but when used in a browser where you can multiple tabs available for doing multiple simultaneos actions, this would be quite convenient.

**Comment by rhahao** [comment]
Thanks @ux-git. We will add this to our backlog. 😊

**Comment by ux-git** [comment]
Perhaps we're close to a standartized solution: https://chromeunboxed.com/tabbed-pwas-for-chromebooks-will-be-a-game-changer-web-apps/

**Comment by rhahao** [comment]
Let’s see how things will change in the future. 😎
