### ISSUE TITLE
Nepali - New Language Request

### ISSUE THREAD

**Issue by shbigyan13** [sws2apps/organized-app#1327]
### Enter the jw.org url to access this language:

https://www.jw.org/ne

**Comment by shbigyan13** [comment]
> @shbigyan13 we can do an AI-based translation of the language, if you send us the list of translations in your language. Afterwards, you will be able to proofread text strings instead of translating everything from scratch.
> 
> Congregation = Assignment = Publisher = Meeting = Midweek meeting = Weekend meeting = Circuit overseer = Student (of a meeting) = Assistant (of a student) = Elder = Ministerial servant = Ministry = Service = Report = Meeting Schedule = Schedule = Pioneer application = Auxiliary pioneer = Regular pioneer = Speaker = Talk = Memorial = Chairman = Prayer = Reader = Meeting workbook = Governing Body Update (video) = Organizational Accomplishments (video) = Branch office = Bethel = Territory =


Hello, I have sent the translation for the words you mentioned in Nepali langauge. Please let me know if you need any assistance on it.

Congregation = मण्डली
Assignment = असाइनमेन्ट
Publisher = प्रकाशक
Meeting = सभा
Midweek meeting = मध्यहप्ताको सभा
Weekend meeting = सप्ताहन्तको सभा
Circuit overseer = क्षेत्रीय निरीक्षक
Student (of a meeting) = विद्यार्थी
Assistant (of a student) = साथी
Elder = एल्डर
Ministerial servant = सहायक सेवक
Ministry = क्षेत्र सेवा
Service = सेवा
Report = रिपोर्ट
Meeting Schedule = सभाको तालिका
Schedule = तालिका
Pioneer application = अग्रगामी आवेदन
Auxiliary pioneer = सहायक अग्रगामी
Regular pioneer = नियमित अग्रगामी
Speaker = वक्ता
Talk = भाषण
Memorial = स्मरणार्थ
Chairman = चेयरम्यान
Prayer = प्रार्थना
Reader = अनुच्छेद पढ्ने
Meeting workbook = अभ्यास पुस्तिका
Governing Body Update (video) = परिचालक निकायको अपडेट (भिडियो)
Organizational Accomplishments (video) = सङ्गठनको उपलब्धि (भिडियो)
Branch office = शाखा कार्यालय
Bethel = बेथेल
Territory = इलाका

**Comment by ux-git** [comment]
@shbigyan13 great, thank you! We will upload AI-made translations later today. Until that, could you please add a few translation suggestions on Crowdin, to let us see you in the members list and assign you the proofreader role?

I'll notify you as soon as the automated translations are uploaded. Thanks a lot for your volunteer spirit!

**Comment by ux-git** [comment]
@shbigyan13 many AI-automated translations have been uploaded, and I'll be uploading the rest over the next few hours. Additionally, you now have the Proofreader role. Click "**Approve**" on the correct strings, or correct some letters/words and **then click Approve**:

<img width="1056" alt="Screenshot 2024-03-23 at 16 11 20" src="https://github.com/sws2apps/organized-app/assets/80993061/629317f4-315b-4271-9ba2-96bfef60aa89">

<br>**Please note:** The "CPE App (current/old version)" folder on Crowdin is a lower priority for translation. It contains strings from the old app version. We're replacing this with the new Organized app. You can skip this folder or quickly proofread it without spending much time. But if you still plan to use the CPE App until the Organized app is released, feel free to translate this folder.
