### ISSUE TITLE
[FEAT] Change Japanese font 

### ISSUE THREAD

**Issue by Kondo-Kazushi** [sws2apps/organized-app#1404]
**Is your feature request related to a problem? Please describe.**
The Japanese font looks strange when the site is displayed in Japanese.

**Describe the solution you'd like**
Use the [Noto Sans Japanese](https://fonts.google.com/noto/specimen/Noto%2BSans%2BJP) instead.

**Describe alternatives you've considered**
Thank you for adding the Japanese site, but this is not Japanese symbols.
Japanese Kanji and Chinese are very similar. But they feel strange to native Japanese users.
![PHOTO-2024-03-30-04-06-44](https://github.com/sws2apps/organized-app/assets/57133756/b2c0ffdd-a348-48d0-bba2-6f5ddde1de4a)

**Additional context**
This site may be even more helpful.
https://heistak.github.io/your-code-displays-japanese-wrong/

**Comment by rhahao** [comment]
Hello @Kondo-Kazushi, thanks for your report. I will try to include this as soon as possible in the preview environment.

**Comment by rhahao** [comment]
@Kondo-Kazushi, could you please review the change here: [Visit Preview](https://organized-app-git-fork-rhahao-main-next-sws2apps.vercel.app), and let me know if it solves this issue?

**Comment by Kondo-Kazushi** [comment]
@rhahao Thank you so much! These are very comfortable😊
