### ISSUE TITLE
[FEAT] Add check for updates button

### ISSUE THREAD

**Issue by ux-git** [sws2apps/organized-app#1419]
**Is your feature request related to a problem? Please describe.**
Yes, on Safari _(already sounds like a joke with number of its issues here and there 😄, but we still have a lot of potential Safari users)_ it takes sometimes a few days to receive the same update as Chrome provides in just a few minutes after release.

**Describe the solution you'd like**
Add a "Check updates" button in "About the app" window, to be able to force-check the new updates. If no updates – fine, show "No updates available" message, but if turns out that there is an update – we can show the normal blue "Update available" message.

**Describe alternatives you've considered**
Clearing caches and cookies, but it doesn't really help. Changing browsers help, but that's not the best solution for some users.

**Additional context**
<img width="1103" alt="Screenshot 2024-04-03 at 17 04 07" src="https://github.com/sws2apps/organized-app/assets/80993061/0645fcdb-f53e-4032-a18c-3419e0cf8f2d">

**Comment by rhahao** [comment]
Thanks @ux-git! Let’s see how can address it. (The way how PWA is updated is completely different to how a native app works, but let’s see how we can help the Safari users 😊)

**Comment by ux-git** [comment]
@rhahao oh, good to know. Let's see if we could somehow force Safari to update the app better and faster 😅

**Comment by ux-git** [comment]
@rhahao can we count the "Force refresh" button as a completed "replacement" of this requested feature? At least, within the existing current PWA technical approaches.

**Comment by rhahao** [comment]
Hi @ux-git: yes, kind of. 😁 So let’s close this for now.
