### ISSUE TITLE
Armenian - New Language Request

### ISSUE THREAD

**Issue by Ikarusell** [sws2apps/organized-app#1453]
### Enter the jw.org url to access this language:

https://www.jw.org/hy/

### Please provide translations for the following terms in your language:

Congregation: Ժողով
Assignment: Դաս
Publisher: Քարոզիչ
Meeting: Համդիպում
Midweek meeting: Միջշաբաթյա հանդիպում
Weekend meeting: Շաբաթավերջի հանդիպում
Circuit overseer: Շրջանաին Վերակացու
Student (of a meeting): Աշակերտ
Assistant (of a student): Օգնական
Elder: Երեց
Ministerial servant: Ծառայող օգնական
Ministry: Ծառայություն
Service: Քարոզ
Report: Հաշվետվություն
Meeting Schedule: Հանդիպման ծրագիր
Schedule: Ծրագիր
Pioneer application: Ռահվիրաի դիմում
Auxiliary pioneer: 
Regular pioneer: Ռահվիրա
Speaker: Հրետոր
Talk: Ելույթ
Memorial: Հիշատակի երեկո
Chairman: Նախագահող
Prayer: Աղոթք
Reader: Ընդերցող
Meeting workbook: Հանդիպման ձերնարկ
Governing Body Update (video): Կարավարիչ մարմնի հաշվետվություն
Organizational Accomplishments (video): Իմչի է հասել մեր կազմակերպությունը
Branch office: Կարավարիչ մարմին
Bethel: Բեթել
Territory:Տարածք

**Comment by ux-git** [comment]
Hi @Ikarusell, thanks for your request! Could you please also fill out all the requested translations, so we could process the AI-powered translation first, for you to proofread it instead of translating everything from scratch?

**Comment by ux-git** [comment]
Thanks @Ikarusell! Now the [Armenian language](https://crowdin.com/project/organized/hy-AM) is already available on Organized project on Crowdin. In the next hours, the AI-translated texts will be uploaded and ready to be proofread.
