### ISSUE TITLE
[Language] - New Language Request (Swedish)

### ISSUE THREAD

**Issue by Logan08691** [sws2apps/organized-app#1477]
### Enter the jw.org url to access this language:

https://www.jw.org/sv

### Please provide translations for the following terms in your language:

Congregation: Församling
Assignment: Uppgift
Publisher: Förkunnare
Meeting: Möte
Midweek meeting: Veckomöte
Weekend meeting: Helgmöte
Circuit overseer: Kretstillsyningsman
Student (of a meeting): Elev
Assistant (of a student): Motpart
Elder: Äldste
Ministerial servant: Församlingstjänare
Ministry: Tjänst
Service: Tjänst
Report: Rapport
Meeting Schedule: Mötesschema
Schedule: Schema
Pioneer application: Pionjäransökan
Auxiliary pioneer: Hjälppionjär
Regular pioneer: Reguljär pionjär
Speaker: Talare
Talk: Tal / Föredrag
Memorial: Minneshögtiden
Chairman: Ordförande
Prayer: Bön
Reader: Läsare
Meeting workbook: Arbetshäfte
Governing Body Update (video): Uppdatering från styrande kretsen
Organizational Accomplishments (video): Vad organisationen uträttar
Branch office: Avdelningskontor
Bethel: Betel
Territory: Distrikt

**Comment by ux-git** [comment]
Thanks @Logan08691 for the request and basic translations. Swedish is now [available on Crowdin](https://crowdin.com/project/organized/sv-SE).
