### ISSUE TITLE
Cebuano - New Language Request

### ISSUE THREAD

**Issue by chessurisme** [sws2apps/organized-app#1482]
### Enter the jw.org url to access this language:

https://jw.org/ceb

### Please provide translations for the following terms in your language:

Congregation: Kongregasyon 
Assignment: Assignment
Publisher: Magmamantala
Meeting: Tigom
Midweek meeting: Midweek nga Tigom
Weekend meeting: Weekend nga Tigom
Circuit overseer: Circuit Overseer
Student (of a meeting): Estudyante (sa meeting)
Assistant (of a student): Assistant (sa estudyante)
Elder: Ansiyano
Ministerial servant: Ministerial Servant
Ministry: Ministeryo
Service: Service 
Report: Report
Meeting Schedule: Schedule sa Tigom
Schedule: Schedule
Pioneer application: Aplikasyon sa Pioneer
Auxiliary pioneer: Auxiliary Pioneer
Regular pioneer: Regular Pioneer
Speaker: Speaker
Talk: Pakigpulong
Memorial: Memoryal
Chairman: Tsirman
Prayer: Pag-ampo
Reader: Magbabasa
Meeting workbook: Workbook sa Tigom
Governing Body Update (video): Update sa Nagamandong Lawas (video)
Organizational Accomplishments (video): Mga Nalampos sa Organisasyon (video)
Branch office: Sangang buhatan
Bethel: Betel
Territory: Teritoryo

### Do you feel fluent to be a proofreader of the language? If yes, please provide your Crowdin username:

Yes, I am native to this language. Chessurisme is my username.

**Comment by ux-git** [comment]
Thank you @chessurisme so much! Your language with AI pre-translation is [already on Crowdin](https://crowdin.com/project/organized/ceb). Now you can proofread the files (excluding the CPE folder).
