### ISSUE TITLE
Portuguese (Portugal) - New Language Request

### ISSUE THREAD

**Issue by PhoenixNomad** [sws2apps/organized-app#1676]
### Enter the jw.org url to access this language:

https://www.jw.org/pt-pt/

### Please provide translations for the following terms in your language:

Congregation: Congregação
Assignment: Designação
Publisher: Publicador
Meeting: Reunião
Midweek meeting: Reunião de semana
Weekend meeting: Reunião de fim de semana
Circuit overseer: Superintendente de circuito
Student (of a meeting): Estudante (de reunião)
Assistant (of a student): Ajudante (de um estudante)
Elder: Ancião
Ministerial servant: 
Ministry: Pregação
Service: Serviço
Report: Relatório
Meeting Schedule: Horário de Reunião
Schedule: Horário
Pioneer application: Petição de pioneiro
Auxiliary pioneer: Pioneiro Auxiliar
Regular pioneer: Pioneiro Regular
Speaker: Orador
Talk: Discurso
Memorial: Memorial
Chairman: Presidente
Prayer: Oração
Reader: Leitor
Meeting workbook: Livro da reunião
Governing Body Update (video): Atualização do Corpo Governante (vídeo)
Organizational Accomplishments (video): Realizações da Organização (vídeo)
Branch office: Filial
Bethel: Betel
Territory: Território

To simplify is better to duplicate the Brazilian, Portuguese files in Crowdin to Portuguese, Portugal and then we just change phrases as needed, since a huge part should be the same.

### Do you feel fluent to be a proofreader of the language? If yes, please provide your Crowdin username:

phoenixnomad

**Comment by ux-git** [comment]
Hi @PhoenixNomad! Thanks for your request and willingness spirit! The [Portuguese](https://crowdin.com/project/organized/pt-PT) language is now available on Crowdin, and you have the proofreader access for reviewing translations. 

We will prepare the AI pre-translations later today, so you will be able to start. Thanks again!
