### ISSUE TITLE
[FEAT] In Japanese, Swap the place of the first and last name

### ISSUE THREAD

**Issue by Kondo-Kazushi** [sws2apps/organized-app#1712]
**Is your feature request related to a problem? Please describe.**
In Japan, names are expressed in the order of last name(姓） + first name（名）, which may cause confusion.

**Describe the solution you'd like**
Swap the place of the first and last name

**Describe alternatives you've considered**
If Organized is displayed in Japanese, please replace First Name and Last Name.
Or choose which order to display from your profile.
<img width="1138" alt="スクリーンショット 2024-05-04 12 46 07" src="https://github.com/sws2apps/organized-app/assets/57133756/0b67d732-564a-4137-bbcc-f0cd0d7ac17f">
![2024-05-04 13 07の画像](https://github.com/sws2apps/organized-app/assets/57133756/a9a6df2e-c95f-47b3-a1d9-bd04ec365202)

**Additional context**
Japanese tends to emphasize the last name more than the first name.
Thank you for tackling this difficult problem!
(These sentences were automatically translated)

**Comment by rhahao** [comment]
Hello @Kondo-Kazushi, thanks for this request. A new update will be released soon to the preview environment that should address this issue. Thank you.
