### ISSUE TITLE
Vietnamese - New Language Request

### ISSUE THREAD

**Issue by tommai4881** [sws2apps/organized-app#1714]
### Enter the jw.org url to access this language:

https://www.jw.org/vi

### Please provide translations for the following terms in your language:

Congregation: Hội thánh
Assignment: Nhiệm vụ
Publisher: Công bố
Meeting: Nhóm họp
Midweek meeting: Nhóm họp giữa tuần
Weekend meeting: Nhóm họp cuối tuần
Circuit overseer: Giám thị vòng quanh
Student (of a meeting): Học viên
Assistant (of a student): Phụ trợ
Elder: Trưởng lão
Ministerial servant: Phụ tá
Ministry: Thánh chức
Service: Rao giảng
Report: Báo cáo
Meeting Schedule: Lịch nhóm họp
Schedule: Lịch trình
Pioneer application: Đơn đăng ký làm Tiên phong
Auxiliary pioneer: Tiên phong phụ trợ
Regular pioneer: Tiên phong đều đều
Speaker: Người nói chuyện
Talk: Buổi nói chuyện
Memorial: Lễ Tưởng Niệm
Chairman: Chủ toạ
Prayer: Cầu nguyện
Reader: Người đọc
Meeting workbook: Chương trình nhóm họp
Governing Body Update (video): Báo cáo của Hội đồng Lãnh đạo
Organizational Accomplishments (video): Những thành quả về mặt tổ chức
Branch office: Văn phòng Chi nhánh
Bethel: Bê-tên
Territory: Vùng

### Do you feel fluent to be a proofreader of the language? If yes, please provide your Crowdin username:

Yes I can proofreader of the language? My crowdin username is baokhang48812002

**Comment by ux-git** [comment]
Hey @tommai4881! Thank you for requesting your language and agreeing to proofread it!

[Vietnamese translation](https://crowdin.com/project/organized/vi) is now available on Crowdin, feel free to go through the blue pre-translated lines and either approve or do necessary edits and then approve text strings.
