### ISSUE TITLE
Please add Portuguese (Portugal) as a language to traanslate

### ISSUE THREAD

**Issue by verdura** [sws2apps/organized-app#2033]
### Enter the jw.org url to access this language:

https://www.jw.org/pt-pt/

### Please provide translations for the following terms in your language:

Congregation: Congregação
Assignment: Designação
Publisher: Publicador
Meeting: Reunião
Midweek meeting: Reunião de semana 
Weekend meeting: Reunião de fim de semana
Circuit overseer: Superintendente de Circuito
Student (of a meeting): Estudante (de uma reunião)
Assistant (of a student): Ajudante (de um estudante)
Elder: Ancião
Ministerial servant: Servo Ministerial
Ministry: Ministério
Service: Serviço
Report: Relatório
Meeting Schedule: Programação das Reuniões 
Schedule: Programação
Pioneer application: Petição de pioneiro
Auxiliary pioneer: Pioneiro Auxiliar
Regular pioneer: Pioneiro Regular
Speaker: Orador
Talk: Discurso
Memorial: Memorial
Chairman: Presidente
Prayer: Oração
Reader: Leitor
Meeting workbook:  Manual de Actividades
Governing Body Update (video): Actualização do Corpo Governante (video)
Organizational Accomplishments (video): Realizações da Organização (video)
Branch office: Filial
Bethel: Betel
Territory: Território

### Do you feel fluent to be a proofreader of the language? If yes, please provide your Crowdin username:

verdura

**Comment by ux-git** [comment]
Hello @verdura! Is [this](https://crowdin.com/project/organized/pt-PT) the correct version of Portuguese? We've already started translating to it, so we could add you as a proofreader to enable you reviewing the translations as well as suggesting new ones.

**Comment by verdura** [comment]
Yep! It is... My mistake!
You can add me if you want...

**Comment by ux-git** [comment]
Great. I've sent you an invitation to join the Crowdin project
