### ISSUE TITLE
[Finnish] - New Language Request)

### ISSUE THREAD

**Issue by Hi-there-how-are-u** [sws2apps/organized-app#2522]
### Enter the jw.org url to access this language:

https://www.jw.org/fi/

### Please provide translations for the following terms in your language:

Congregation: Seurakunta
Assignment: Tehtävä
Publisher: Julistaja
Meeting: Kokous
Midweek meeting: Viikkokokous
Weekend meeting: Viikonlopun kokous
Circuit overseer: Kierrosvalvoja
Student (of a meeting): Oppilas
Assistant (of a student): Avustaja
Elder: Vanhin
Ministerial servant: Avustava palvelija
Ministry: Kenttäpalvelus
Service: Palvelu
Report: Raportti
Meeting Schedule: Kokousohjelma
Schedule: Ohjelma
Pioneer application: Tienraivaaja anomus
Auxiliary pioneer: Osaaikainen tienraivaaja
Regular pioneer: Vakituinen tienraivaaja
Speaker: Puhuja
Talk: Esitelmä
Memorial: Muistonvietto
Chairman: Puheenjohtaja
Prayer: Rukous
Reader: Lukija
Meeting workbook: Työkirja
Governing Body Update (video): 
Organizational Accomplishments (video): Hallintoelimen tilannepäivitys (video)
Branch office: Haaratoimisto
Bethel: Betel
Territory: Kenttäalue

### Do you feel fluent to be a proofreader of the language? If yes, please provide your Crowdin username:

Hi-there-how-are-u

**Comment by ux-git** [comment]
Hey @Hi-there-how-are-u, thanks for your contribution! Here is the [Finnish project on Crowdin](https://crowdin.com/project/organized/fi). Happy translating!

@rhahao, could you please import the Finnish songs as well?

**Comment by rhahao** [comment]
The songs have been imported. Thanks.
