### ISSUE TITLE
[Language] - New Language Request

### ISSUE THREAD

**Issue by JGMBRIELLE** [sws2apps/organized-app#2843]
### Enter the jw.org url to access this language:

https://www.jw.org/nl/

### Please provide translations for the following terms in your language:

Congregation: Gemeente
Assignment: Toewijzing
Publisher: Verkondiger
Meeting: Vergadering
Midweek meeting: Doordeweekse vergadering
Weekend meeting: Weekend vergadering
Circuit overseer: Kringopziener
Student (of a meeting): Leerling
Assistant (of a student): Assistent
Elder: Ouderling
Ministerial servant: Dienaar
Ministry: Velddienst
Service: Dienst
Report: Bericht
Meeting Schedule: Vergaderschema
Schedule: Schema
Pioneer application: Aanmelding voor de gewone pioniersdienst
Auxiliary pioneer: Hulppionier
Regular pioneer: Gewone pionier
Speaker: Spreker
Talk: Lezing
Memorial: Avondmaal
Chairman: Voorzitter
Prayer: Gebed
Reader: Lezer
Meeting workbook: Werkboek
Governing Body Update (video): Besturende Lichaam update
Organizational Accomplishments (video): Wat de organisatie heeft bereikt
Branch office: Bijkantoor
Bethel: Bethel
Territory: Gebied

### Do you feel fluent to be a proofreader of the language? If yes, please provide your Crowdin username:

JanosM

**Comment by ux-git** [comment]
Hey @JGMBRIELLE 👋 Thanks a lot for willingness spirit! Your language is already [available on Crowdin](https://crowdin.com/project/organized/nl).

In the coming hours we will upload AI pre-translations, which will serve as a good starting point. You can go through all of them and either approve or edit and then approve each text string. Of course, they won't be all correct, but still it saves many hours of translation time.

Thanks again, and in case of any questions, feel free to ask! 🤝

**Comment by ux-git** [comment]
Also, @rhahao please add the language also to the EPUB parser + parse the Songs once you have a chance. And I'll add it to the Notifications and Release Notes project on Crowdin.

**Comment by ux-git** [comment]
@JGMBRIELLE the AI translations are uploaded, so happy translating!
