### ISSUE TITLE
Slovenian - New Language Request

### ISSUE THREAD

**Issue by brobic74** [sws2apps/organized-app#2864]
### Enter the jw.org url to access this language:

https://www.jw.org/sl/

### Please provide translations for the following terms in your language:

Congregation: občina
Assignment: dodelitev
Publisher: oznanjevalec
Meeting: shod
Midweek meeting: shod med tednom
Weekend meeting: shod ob koncu tedna
Circuit overseer: okrajni nadzornik
Student (of a meeting): učenec
Assistant (of a student): sogovornik
Elder: starešina
Ministerial servant: strežni služabnik
Ministry: oznanjevanje
Service: služba
Report: poročilo
Meeting Schedule: razpored shodov
Schedule: razpored
Pioneer application: prošnja za pionirsko službo
Auxiliary pioneer: pomožni pionir
Regular pioneer: redni pionir
Speaker: govornik
Talk: govor
Memorial: spominska slovesnost
Chairman: predsedujoči
Prayer: molitev
Reader: bralec
Meeting workbook: delovni zvezek
Governing Body Update (video): Poročilo Vodstvenega organa (videoposnetek)
Organizational Accomplishments (video): Organizacijski dosežki (videoposnetek)
Branch office: podružnični urad
Bethel: betel
Territory: področje

### Do you feel fluent to be a proofreader of the language? If yes, please provide your Crowdin username:

Yes, I can proofread into Slovenian.  My Crowdin username is brobic74.

**Comment by ux-git** [comment]
Thank you @brobic74 for the new language request and your willingness to contribute! [Slovenian language](https://crowdin.com/project/organized/sl) is already available on Crowdin, and the AI pre-translations are ready. 

You have received the proofreader role invitation, so once you're ready, feel free to start. In case of any questions, don't hesitate to ask :) 

@rhahao I've also created the [Notifications and releases](https://crowdin.com/project/organized-miscellaneous) project as well. Could you sync the Kingdom Songs + set up the [EPUB parser](https://crowdin.com/project/cpe-jw-epub-parser) in addition?
