### ISSUE TITLE
Inconsistent display of "Closing Prayer" in Portuguese translation

### ISSUE THREAD

**Issue by fschein** [sws2apps/organized-app#2938]
**Describe the bug**
The system appears to display the incorrect prayer label in Portuguese - BR. Where "Closing Prayer" should appear, it currently shows the text for "Opening Prayer" from the "Prayer" string. This affects all templates and areas within the system where prayers are labeled.

**To Reproduce**
1. Go to any template or screen displaying prayer sections in the Portuguese - BR language environment.
2. Observe how the term for the final prayer incorrectly displays as the initial prayer.
3. Check both test and preview environments to confirm the discrepancy.

**Expected behavior**
The system should display "Oração final" in the designated sections for the final prayer, rather than repeating the term for the initial prayer.

**Screenshots**
![image](https://github.com/user-attachments/assets/3214a29e-d038-4ffe-9b70-88daa31c50cd)
![image](https://github.com/user-attachments/assets/539093cc-56f3-48fd-bea7-b11e53e84232)

**Desktop (please complete the following information):**
 - OS: Fedora Linux Workstation 41
 - Waterfox G6.0.20 (64-bit)

**Additional context**
**PS**: I’ve already modified the "Prayer" string to "Oração," without specifying opening or closing, in Crowdin.

**Comment by rhahao** [comment]
Hello @fschein, I’ll take a look at this and provide additional info asap. Thank you.

**Comment by rhahao** [comment]
Hello @fschein, upon checking in the code, since you already updated the translation in Crowdin, and now the PR #2927 has been merged and deployed, I believe this is no longer an issue. Thank you.
