### ISSUE TITLE
Translation into Estonian

### ISSUE THREAD

**Issue by wikmanipoiss** [sws2apps/organized-app#2950]
### Enter the jw.org url to access this language:

https://www.jw.org/et

### Please provide translations for the following terms in your language:

Congregation: Kogudus
Assignment: Ülesanne
Publisher: Kuulutaja
Meeting: Koosolek
Midweek meeting: Nädalasisene koosolek 
Weekend meeting: Nädalavahetusel toimuv koosolek
Circuit overseer: Ringkonnaülevaataja
Student (of a meeting): Õpilane ( kõneülesanne)
Assistant (of a student): Abiline ( kõneülesanne)
Elder: Kogudusevanem
Ministerial servant: Koguduseabiline
Ministry: Kuulutustöö
Service: Teenistus
Report: Kokkuvõte
Meeting Schedule: Koosoleku kava
Schedule: Kava
Pioneer application: Üldpioneerteenistuse avaldus
Auxiliary pioneer: Abipioneer
Regular pioneer: Üldpioneer
Speaker: Kõnepidaja
Talk: Kõne
Memorial: Mälestusõhtu
Chairman: Juhataja
Prayer: Palve
Reader: Lugeja
Meeting workbook: Koosoleku töövihik
Governing Body Update (video): Juhtiva kogu erisaade (video)
Organizational Accomplishments (video): Organisatsiooni saavutused (video)
Branch office: Harubüroo
Bethel: Peetel
Territory: Territoorium

### Do you feel fluent to be a proofreader of the language? If yes, please provide your Crowdin username:

denis.raudsepp

**Comment by ux-git** [comment]
Hello! [Estonian](https://crowdin.com/project/organized) has been added to the Organized app translation project. You should have the translator and proofreader role right now. We've uploaded AI-powered pre-translations for you to make the process easier. Some will require correction, but many short and general terms will be translated well.

Estonian is now also available in some smaller projects such as [Notification and releases](https://crowdin.com/project/organized-miscellaneous) and [JW EPUB parser](https://crowdin.com/project/cpe-jw-epub-parser) projects as well. @rhahao could you please sync the songs and add Estonian to EPUB Parser once it's translated?

If you have any questions, feel free to ask.
