### ISSUE TITLE
Missing translations in two sections of the About page

### ISSUE THREAD

**Issue by fschein** [sws2apps/organized-app#2989]
**Describe the bug**
Two sections on the About page are not displaying their respective translations.
The affected strings are:

- Reports (key: `tr_reportsAboutPage`)
- Appointed brothers (key: `tr_appointedBrothersAboutPage`)

**To Reproduce**
1. Go to the About page.
2. Look for the sections containing the affected strings (Reports and Appointed brothers)
3. Notice that they are not translated when the language is set to anything other than English.

**Expected behavior**
Each string should display its correct translation based on the selected language.

**Screenshots**
![image](https://github.com/user-attachments/assets/8d19c902-ca31-4327-a655-3de7ff0883a9)
![image](https://github.com/user-attachments/assets/43b38422-0461-49d9-bc10-4fa00b6c16f7)

Desktop:

- OS: Fedora Workstation 41
- Browser: Waterfox G6.0.20

**Additional context**
This issue seems to occur across all non-English languages.

**Comment by fschein** [comment]
The strings are translated correctly:
![image](https://github.com/user-attachments/assets/a8e2e810-5f34-480d-9a56-ab19ef35638e)
![image](https://github.com/user-attachments/assets/c4d8c567-d126-4181-94d8-1f2810ab87ed)

**Comment by ux-git** [comment]
Thank you for reporting! 

@mrtavor could you please take look and fix this?

**Comment by mrtavor** [comment]
Hi @fschein @ux-git, of course.

**Comment by mrtavor** [comment]
Fixed 👍
