### ISSUE TITLE
New Language Request: Kreyòl ayisyen (Haitian Creole)

### ISSUE THREAD

**Issue by fschein** [sws2apps/organized-app#3064]
### Enter the jw.org url to access this language:

https://www.jw.org/ht/

### Please provide translations for the following terms in your language:

In the South of Brazil, we have many congregations that speak Haitian Creole. And of course, the brothers from Haiti will benefit. I recommended the app to a brother, and he became interested in translating it and suggesting it for some of the congregations.

Congregation: Kongrégasyon
Assignment: Atribisyon
Publisher: Piblikatè
Meeting: Reyinyon
Midweek meeting: Reyinyon nan mitan semèn
Weekend meeting: Reyinyon fen semèn
Circuit overseer: Supervizè sikwi
Student (of a meeting): Etidyan (nan yon reyinyon)
Assistant (of a student): Asistan (yon etidyan)
Elder: Ansyen
Ministerial servant: Sèvitè ministè
Ministry: Ministè
Service: Sèvis
Report: Rapò
Meeting Schedule: Orè reyinyon
Schedule: Orè
Pioneer application: Aplikasyon pou pyonye
Auxiliary pioneer: Pyonye okzitilè
Regular pioneer: Pyonye regilye
Speaker: Pale
Talk: Diskou
Memorial: Memorial
Chairman: Prezidan
Prayer: Lapriyè
Reader: Lecktè
Meeting workbook: Liv travay reyinyon
Governing Body Update (video): Mizajou kòdirèksyon (videyo)
Organizational Accomplishments (video): Reyalizasyon òganizasyon (videyo)
Branch office: Biwo branch
Bethel: Betèl
Territory: Teritwa

### Do you feel fluent to be a proofreader of the language? If yes, please provide your Crowdin username:

No, but you can add me as a proofreader. The person who will translate hasn't joined Crowdin yet. My username is @fschein

**Comment by ux-git** [comment]
Thank you @fschein! Here's the pre-translated Haitian Creole on Crowding, ready to be proofread: https://crowdin.com/project/organized/ht

You do already have the corresponding proofreader role, so you can approve the translation together with the native speaker, or once the native speaker joins Crowdin, let me know and I'll assign them the proofreader role to do this.

Other Crowdin projects such as [Notifications](https://crowdin.com/project/organized-miscellaneous) and [JW EPUB](https://crowdin.com/project/cpe-jw-epub-parser) parser do also have this language now.

––––

@rhahao could you sync the songs?
