### ISSUE TITLE
Create a new string for "Security overseer" to differentiate from existing "Security" string

### ISSUE THREAD

**Issue by fschein** [sws2apps/organized-app#3065]
**Describe the bug**
In Brazil, we do not use the term "Security" for the role associated with the security of the Kingdom Hall. Instead, we use a term like "Entrancy overseer." The issue is that the current translation of "Security" is being used in both the Kingdom Hall securtity context and the security section of the app settings. 

**To Reproduce**
This issue cannot be reproduced yet, as the app has not been launched. However, the problem is anticipated because the same string ("Security") will be used for two different contexts: one for the Kingdom Hall "Security" role and the other for the security-related settings.

**Expected behavior**
We expect that "Entrancy overseer" (in the context of the security of the KH) has a separate string, so it can be translated appropriately to "Indicador da entrada" in Portuguese, distinct from the security section, which should maintain its current translation.

**Screenshots**
![image](https://github.com/user-attachments/assets/51aa739f-71ab-4546-b63d-3631b265eefd)
![image](https://github.com/user-attachments/assets/38495d0a-4ed5-472c-ac17-c3a1ec10813a)

**Additional context**
The term "Entrancy overseer" is used in Brazil for the role of overseeing the security of the Kingdom Hall, as outlined in the doc *Plano de Segurança (S-288)*, and it should be distinguished from the "Security" section in the app settings. We request that a new string be created to avoid confusion and ensure that the translation is correct for both contexts.

**Comment by mrtavor** [comment]
Hi @fschein, thank you for helping to improve the app, especially for this report and the great idea. At the moment, the new string has already been added for translation - https://crowdin.com/editor/organized/2020/en-ptbr?view=comfortable#53062.
