### ISSUE TITLE
Cannot create an account with email

### ISSUE THREAD

**Issue by fschein** [sws2apps/organized-app#3099]
**Describe the bug**
When attempting to create an account with an email address, the email is not sent, and an error appears in the console.

**To Reproduce**
1. Go to the account creation page;
3. Select 'Baptized brother';
4. Select 'Continue with Email';
5. Write some Email;
6. See the error.

**Expected behavior**
Should send a confirmation email without errors.

**Screenshots**
![image](https://github.com/user-attachments/assets/2b40735a-232e-438f-b2f8-b7a2c115cad6)

**Desktop (please complete the following information):**
- Fedora Workstation 41

**Additional context**
....

**Comment by fschein** [comment]
The error occurs when trying to continue with Google as well
![image](https://github.com/user-attachments/assets/af62cd64-d4e4-41f4-9605-af76ac84e09e)

**Comment by rhahao** [comment]
Hello @fschein, sorry for the inconvenience this caused. The restart of the server to support the changes takes longer than expected. I’ll let you know when it’s online. Thank you.

**Comment by fschein** [comment]
No problem. Thanks for the quick response!

**Comment by rhahao** [comment]
It is back online now @fschein. Thanks for your patience.
