### ISSUE TITLE
[FIX] Master key request

### ISSUE THREAD

**Issue by joaochris** [sws2apps/organized-app#3101]
When logging in, it's asking me for a master key, but I didn't configure it in the previous version :D

![Screenshot_2024-12-01-00-33-33-494_com.android.chrome.jpg](https://github.com/user-attachments/assets/b75ba094-b105-4911-9153-0bbe1fe39845)

I didn't add anything, I minimized the browser and after a while, when I returned to it, this appeared:

![Screenshot_2024-12-01-00-42-58-195_com.android.chrome.jpg](https://github.com/user-attachments/assets/84b68525-ea3b-48b7-a041-e06308d0cfa4)

**Comment by rhahao** [comment]
Hi @joaochris, it solved itself then. 😊

**Comment by rhahao** [comment]
I am closing this for now. If the problem reappears again, just create a new issue and I’ll take a look at it again. Thanks.
