### ISSUE TITLE
"tr_errorGeneric" error during registration

### ISSUE THREAD

**Issue by mrtavor** [sws2apps/organized-app#3105]
**Describe the bug**
I cannot register myself through Google account

**To Reproduce**
1. Open Organized
2. Click the "Baptized brother" button
3. Then select "Continue with Google account" (choose the account)
4. After that, this error appears

**Expected behavior**
I expected to see that I had successfully registered my account.

**Screenshots**
![Screenshot_20241201-121117.png](https://github.com/user-attachments/assets/3e817cc3-0461-4a15-a8cc-776c60075d8a)

**Smartphone (please complete the following information):**
 - Device: [CMF Phone 1]
 - OS: [Nothing OS 2.6]
 - Browser [I installed the PWA on my phone through Chrome]
 - Version [3.0.0]

**Additional context**
Before attempting to register a second time, I cleared the app's cache, but it did not help.

**Comment by rhahao** [comment]
Hi @mrtavor, I was not able to duplicate this but I will deploy new changes soon and it will display additional message to the errors. Check it after the update let me know that error is thrown. Thanks.

**Comment by mrtavor** [comment]
Hi @rhahao, since the publication of this issue, I haven't encountered this error anymore. Perhaps it was something unique and only occurred on my phone.

**Comment by rhahao** [comment]
That’s great @mrtavor. Feel free to re-open this if it occurs again in the future. Thanks.
