### ISSUE TITLE
Error generating invitation code

### ISSUE THREAD

**Issue by fschein** [sws2apps/organized-app#3106]
**Describe the bug**
An error occurs when attempting to generate an invitation code.

**To Reproduce**

1. Go to "Manage Access."

2. Select a user.

3. Click on "Generate Code."

4. Observe the error.

**Expected behavior**
The system should successfully generate an invitation code without any errors.

**Screenshots**
![Screenshot_20241201-085107_Chrome](https://github.com/user-attachments/assets/0df1924d-0087-4e76-aa57-62f7ba06bfc6)

Smartphone (please complete the following information):

Device: Zenfone9

OS: Android 14

Browser: Chrome

**Additional context**
...

**Comment by fschein** [comment]
I will, thank you!

**Comment by fschein** [comment]
Hey @rhahao, still can't generate the code:

![Screenshot_20241201-161243_Chrome](https://github.com/user-attachments/assets/b2ade28d-1aca-421a-aee6-176ce6ad776f)

**Comment by fschein** [comment]
@rhahao, it worked now 😊

**Comment by rhahao** [comment]
Great. We are closing this one then. 😊

**Comment by fschein** [comment]
Working now.
