### ISSUE TITLE
[FIX] No backup

### ISSUE THREAD

**Issue by joaochris** [sws2apps/organized-app#3108]
My data from the previous version did not appear in this one :( there is no data.

**Comment by rhahao** [comment]
Hi @joaochris, it appears like the migration did not occur for your congregation in such case. As we announced previously, in order for the data to be migrated from CPE to Organized:

- the congregation must already use the new https://organized-app.com address (before today), and
- the latest recent data must be restored by one of the administrator in the device he will be using to do the migration.

Without this, unfortunately, CPE data is no longer recoverable.

**Comment by joaochris** [comment]
Yes, I already used it on this same site. How do I restore?

**Comment by rhahao** [comment]
The migration will automatically start if you already had the CPE in that URL before today. If not, that means the data is not there.

**Comment by joaochris** [comment]
> The migration will automatically start if you already had the CPE in that URL before today. If not, that means the data is not there.

I followed the announcement exactly before the launch, I can't lose the backup, it's a lot of information. Does the migration take long to happen?

**Comment by rhahao** [comment]
The migration will not take that long. The only condition that it will run that it must find the CPE data in the current browser you are using now. Right after you are opening the app URL, the migration window will be directly displayed if it’s there.

**Comment by rhahao** [comment]
You can use this [IndexedDB Exporter Chrome extension](https://chromewebstore.google.com/detail/indexeddb-exporter/kngligbmoipnmljnpphhocajldjplgcj?hl=en-US&utm_source=ext_sidebar) (if you use Chromium browser) to check if it can find the cpe_sws database in your browser. If yes, then export it and you can import it back later when I add the import/export data feature very soon. Thanks.

**Comment by joaochris** [comment]
UFAAAA 😅. A brother here still used the old website, and I was able to export the data with this .json format extension. Just waiting for this feature to be implemented to import my data 😍

**Comment by rhahao** [comment]
Okay, that’s great. At least you have this backup. Stay tuned for new import/export feature. 😊
