### ISSUE TITLE
Weekend meeting schedule PDF shows ID instead of speaker name

### ISSUE THREAD

**Issue by fschein** [sws2apps/organized-app#3111]
**Describe the bug**
The name of the speaker is replaced by an ID in the exported weekend meeting schedule PDF.

**To Reproduce**
1. Export a weekend meeting schedule;
2. Open the PDF;
3. Observe that the speaker's name is displayed as an ID instead.

**Expected behavior**
The PDF should display the speaker's name correctly instead of an ID.

**Screenshots**
![Novo Projeto(1)](https://github.com/user-attachments/assets/0af0fc9f-b0c6-4d4c-a163-3384871123e7)

**Desktop (please complete the following information):**
 - Fedora WS 41
 - Firefox

**Additional context**
...

**Comment by fschein** [comment]
The issue seems to occur when saving the speaker, as observed in the screenshot:

![Screenshot_20241201-160110_Chrome](https://github.com/user-attachments/assets/738f1ead-3024-4a58-8d58-a3c663049f0a)

**Comment by fschein** [comment]
The list of speakers from other congregations that I had registered has simply disappeared.

**Comment by rhahao** [comment]
> The list of speakers from other congregations that I had registered has simply disappeared.

@fschein: please check and verify this once more and if it keeps occurring, create a new issue and provide the steps to reproduce it. For now, I cannot duplicate that so if you provide detailed steps on what did you do in your end that may trigger that deletion, that really helps. Thanks.
