### ISSUE TITLE
Text visibility issue when adding a new member in dark mode

### ISSUE THREAD

**Issue by fschein** [sws2apps/organized-app#3112]
When adding a new user in dark mode, the text remains dark, making it difficult to read:

![Screenshot_20241201-160734_Chrome](https://github.com/user-attachments/assets/a0d9bd12-6f3f-4165-911f-24d6e416a49d)

**Comment by ux-git** [comment]
@FussuChalice could you fix this please? 

Additionally another missing color variable was found on the Congregation settings page → Congregation privacy  → Master key and also Access code.

https://github.com/user-attachments/assets/a80e5350-8293-4ef6-bd6c-2349fc6c282f

**Comment by ux-git** [comment]
Or @rhahao if you could do this faster, feel free to do so 😅
