### ISSUE TITLE
[FIX] Infinite loading & animation is not vertically centered

### ISSUE THREAD

**Issue by mrtavor** [sws2apps/organized-app#3115]
**Describe the bug**
1. After my account was removed from the Congregation and the login page was reloaded, I now experience infinite loading.
2. The loading animation is not vertically centered relative to the block where it should be.

**To Reproduce**
1. I registered.  
3. ux-git granted me permissions (extra ones) and later revoked them.  
4. I didn’t log into the account because it asked for a Master Key.  
5. ux-git deleted my account.  
6. I registered again using Incognito mode in the Arc browser, and ux-git added me back.  
7. Now everything works fine in Incognito mode or another browser (Chrome), but the main browser (Arc) loads indefinitely.  

**Expected behavior**
I expected that after refreshing the page, I would be logged out of the account and able to log in again.

**Screenshots**
![image](https://github.com/user-attachments/assets/9f665fce-d894-42c7-81bf-79c599b862fd)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Arc]
 - Version [3.0.0]

**Additional context**
I cleared the cache and cookies.

**Comment by mrtavor** [comment]
I was able to reproduce this bug on another phone today.

**To Reproduce**
Steps to reproduce the behavior:

1. Opened Organized in Safari and installed the PWA.  
2. Opened the app and registered as a baptized brother.  
3. My email was linked to a person in the congregation.  
4. Reloaded the page in the PWA or simply restarted the app (if needed, logged back in using the same Google Account that was added).  
5. While on the page prompting me to enter the congregation code to join, I tried switching to a browser where Organized was already open and logged in with the same account (this step triggered the bug on the CMF Phone 1). If everything works fine and the browser page asking for the access code loads without errors, proceed to the next step.  
6. Go back to the Organized PWA, enter the access code, and join your congregation.  
7. Now, return to the browser and reload Organized. If everything works fine, try logging in again using the same account previously used for the PWA.  
8. At this point, I encountered an infinite loading screen in Safari.  

**Screenshots:**
![image](https://github.com/user-attachments/assets/28610b32-e6be-43cd-8db7-3effdbc1d19e)


**Smartphone (please complete the following information):**
 - Device: [iPhone 13 Pro Max]
 - OS: [IOS 18.1.1]
 - Browser [Safari]
 - Version [3.1.0]
 
**Additional context:**
This happens not only in Safari; I also experienced it in Chrome, Arc browsers, and the PWA on PC and phones with different OS

**Comment by rhahao** [comment]
Thanks @mrtavor. I’ll try to duplicate it. Just to clarify: so is this happening only if I use two different browsers or two devices at the same time, during the login process?

**Comment by mrtavor** [comment]
Personally, I was only able to replicate this on a phone, using a single phone and accessing the service through both a browser and a PWA for login.

**Comment by fschein** [comment]
I opened an issue that may be related to this subject. Please, take a look: [#3126](https://github.com/sws2apps/organized-app/issues/3126)
