### ISSUE TITLE
[FIX] Error when selecting and deselecting student assignments on the persons page

### ISSUE THREAD

**Issue by fschein** [sws2apps/organized-app#3125]
**Describe the bug**
On the "Person" page, after clicking "Select All" for student assignments, it is not possible to deselect all or any individual item. The "Deselect All" functionality does not work, and individual items cannot be deselected either, leaving all assignments still selected.

**To Reproduce**
1. Navigate to a "Person" page;
2. Click "Select All" for student assignments;
3. Attempt to click "Deselect All.";
4. Notice that the action does not clear the selections;
5. Attempt to deselect an individual item;
6. Notice that the individual item remains selected.

**Expected behavior**
Clicking "Deselect All" should successfully clear all previously selected student assignments. Additionally, individual items should be deselectable as expected.

**Video**

https://github.com/user-attachments/assets/00fdc209-2122-4416-9f22-d73b846d9729

**Desktop (please complete the following information):**
 - OS: [Fedora WS 41]
 - Browser [Firefox

**Comment by ux-git** [comment]
Good catch! I do also have the same bug, in the test mode too. Seems like the tricky "Assistant only" option causes this issue, since other parts of the meeting are not affected.

**Comment by ux-git** [comment]
> a simple way to resolve it would be by keeping the 'Assistant only' option as 'Assistant' and making it part of the assignments

@rhahao or maybe the Assistant only can stay at the same place but technically not be a part of the list? This way the assignment list will be separated from the 'Assistant only' option and hopefully won't interfere during the selection process?
