### ISSUE TITLE
Error when authenticating a baptized user

### ISSUE THREAD

**Issue by fschein** [sws2apps/organized-app#3126]
**Describe the bug**
An error occurs when assigning any role to a baptized user on the "Manage Access to Organized" page. If the user logs in without any assigned roles, authentication works without issues. However, as soon as a role is granted, an authentication error related to Firebase appears in the console.

**To Reproduce**

1. Navigate to the "Manage Access to Organized" page.
2. Ensure the baptized user has no roles assigned.
3. Log in as the baptized user — authentication works correctly.
4. Assign any role to the baptized user on the "Manage Access to Organized" page.
5. Attempt to log in again as the baptized user.
6. Observe the authentication error in the console, which indicates an issue with Firebase.

**Expected behavior**
Baptized users should be able to log in and access their account regardless of whether they have roles assigned.

**Screenshots**
![image](https://github.com/user-attachments/assets/08114dd8-74ab-4d8b-b013-5a79b5c0b861)

**Desktop (please complete the following information):**
 - OS: Fedora WS 41 
 - Browser Firefox

**Smartphone (please complete the following information):**
 - OS: Android 11
 - Browser Google Chrome

**Additional context**
This issue seems to specifically affect baptized users when roles are assigned and is tied to Firebase authentication. Without any assigned roles, login works as expected.
This issue might be related to issue [#3115](https://github.com/sws2apps/organized-app/issues/3115).

**Comment by rhahao** [comment]
Hi @fschein, thanks for this report. From this report, it appears to be only a Firebase error not from the app or the api itself. I’ll take a look and try to duplicate to see what’s happening. Thanks.

**Comment by ux-git** [comment]
@fschein is the issue still present, or already gone since the time you created this issue?

**Comment by fschein** [comment]
Hey @ux-git, I believe this was solved on #3115
