### ISSUE TITLE
[FIX] Error accessing the test mode

### ISSUE THREAD

**Issue by joaochris** [sws2apps/organized-app#3130]
https://test.organized-app.com/

![Screenshot_2024-12-03-13-40-42-882_com.android.chrome.jpg](https://github.com/user-attachments/assets/226e9b6e-f01e-479c-9f39-67905b0be375)

**Comment by mrtavor** [comment]
Hi @joaochris, thank you for your report. I tried accessing the test mode on my phone through your link, and everything works fine for me.

![Screenshot_20241203-191554.png](https://github.com/user-attachments/assets/58ea72d8-fa47-4f9f-96b4-27d7c9ec9c92)

**Comment by joaochris** [comment]
> Hi @joaochris, thank you for your report. I tried accessing the test mode on my phone through your link, and everything works fine for me.
> 
> Can you tell please what you were doing before you encountered this error? Maybe I can reproduce it.
> 
> ![Screenshot_20241203-191554.png](https://github.com/user-attachments/assets/58ea72d8-fa47-4f9f-96b4-27d7c9ec9c92)

I don't know how, but it was resolved. Thank you very much! @mrtavor and to everyone.

**Comment by joaochris** [comment]
> @joaochris in case this or something similar happens once again, could you also take a screenshort of the developer tools (F12) → Console? This will provide valuable context to catch such issues, or even more rare ones. 

Of course! In this specific case, it didn't work because I was using Google Chrome on my cell phone, there's no way to open the console on it. So I went to test an app that has a way to catch the console error and it didn't appear there.
