### ISSUE TITLE
[FIX] Login layout bugs

### ISSUE THREAD

**Issue by ux-git** [sws2apps/organized-app#3135]
**Describe the bug**

The following two bugs have happened today at the same time during the login process.

1. First bug happens for quite some time already, when a login on mobile (usually using Google account) is cancelled or somehow redirected between PWA and Chrome to login, or something else, then the login and the next step are fit into the same card side-by-side:
![photo_2024-12-03 23 01 50](https://github.com/user-attachments/assets/13697492-28e5-43cb-a44b-bdb6224d1983)

3. And for the short time after clicking "Baptized brother" option, the Organized animated logo is competely within the blue section with illustrations:

https://github.com/user-attachments/assets/83ed36e9-1156-45c7-8f96-b712cf494692

**Smartphone (please complete the following information):**
 - Device: Google Pixel
 - OS: Android
 - Browser: PWA installed via Chrome

**Additional context**
Can't get the specific steps to reproduce, but this visual bug is definitely since long time already. But the context is: I deleted the preview Organized PWA, then installed the new release version as PWA, then logged in with Google account and once back, I saw these two bugs.

**Comment by mrtavor** [comment]
I have the same issue. However, I found a way to replicate it on different devices. You need to log in using an account that is already added to the congregation.

1. Log in through Google Account.
2. You land on a page where you need to enter the congregation code.
3. Reload the page.
4. You encounter a bug with two functions displayed on the same page.

![Screenshot_20241203-234325~2.png](https://github.com/user-attachments/assets/bd5aa317-97e3-4780-8988-30eade35ada7)

**Comment by rhahao** [comment]
@ux-git, @mrtavor: in version 3.2.0, fix was introduced to mitigate this issue. Could you please check and see if you are still seeing it occurring? Thanks.

**Comment by mrtavor** [comment]
Hi @rhahao, unfortunately, when I reload the page where the congregation password needs to be entered, I still encounter this issue.

**Comment by rhahao** [comment]
Ok thanks. I’ll check it again.
