### ISSUE TITLE
[FIX] PDF alignment – when the part name is too long, this breaks the alignment 

### ISSUE THREAD

**Issue by joaochris** [sws2apps/organized-app#3151]
![image](https://github.com/user-attachments/assets/480e2071-2569-4f8a-ad81-6b1ba4045711)

![image](https://github.com/user-attachments/assets/12f71681-0249-4994-826a-84acd912a908)

![image](https://github.com/user-attachments/assets/690a070c-e481-4576-9488-6076b9fdca75)

Suggestion for the title text to break before reaching the end of the box, perhaps this will prevent it from breaking the alignment.

**Comment by ux-git** [comment]
Thanks! @rhahao Plus, the horizontal alignment of the time stamp can be moved from the middle to top to align with "View weekly meetings" page and align well with the meeting part title better.

**Comment by ux-git** [comment]
Also, the last words row has no semi-red tint for the background, even though it should've had according to white-tinted-white-tinted sequence.
