### ISSUE TITLE
[FIX] Translation in Tagalog language

### ISSUE THREAD

**Issue by crldv** [sws2apps/organized-app#3162]
**Describe the bug**
Some words are not translated into Tagalog (see screenshot attached)

**To Reproduce**
1. Go to 'Language'
2. Click on 'Tagalog'
3. Click on 'Midweek meeting'
4. Click on 'Export'
6. Choose start and end month
7. Check 'Midweek meeting schedule (S-140)'
8. Click on 'Standard' then 'Export'
9. View the PDF file and see error

**Expected behavior**
Some words in the exported schedule should be in Tagalog language such:
1. 'Midweek Meeting Schedule'
2. Date
3. Meeting sections ('Treasure from God's Word', etc)
4. Opening comments & Concluding comments
5. Prayer
6. Conductor, Reader.

**Screenshots**
![IMG_20241206_210203.jpg](https://github.com/user-attachments/assets/064961ad-3966-4402-aebd-19c8974b9fb5)

**Smartphone (please complete the following information):**
 - Device: Realme 8 Pro
 - OS: realme UI 4.0, Android 13
 - Browser: Kiwi Browser
 - Version 124.0.6327.4

**Comment by ux-git** [comment]
Plus, I noticed that the very first row only has the 0 before the 5:30. ✍️

**Comment by crldv** [comment]
About the time, I've changed it to 5:30 AM from 5:30 PM because the template displays in 24-hour format 😅

**Comment by ux-git** [comment]
Support the 12-h time format ✍️ 😄
