### ISSUE TITLE
[FEAT] Additional button for adding time

### ISSUE THREAD

**Issue by crldv** [sws2apps/organized-app#3171]
**Is your feature request related to a problem? Please describe.**
Can't add minutes when adding time

**Describe the solution you'd like**
Another button that can add minutes. This app feature is from the Ministry Assistant app widget(see screenshot)![IMG_20241207_153225.jpg](https://github.com/user-attachments/assets/000a01e0-5a7c-46f8-aa6e-83dbe70f2aa7)
![Screenshot_2024-12-07-15-25-52-82_d7df185609163aa0123e4051a0303ac2.jpg](https://github.com/user-attachments/assets/cc5ac3e2-aa4c-4941-8c49-d7f23b2d5592)

**Describe alternatives you've considered**
We could also consider another calendar design. Like it is anchored in the screen, not following when scrolling. Like the calendar in ministry assistant app too (see screenshot)
![Screenshot_2024-12-07-15-23-54-84_d7df185609163aa0123e4051a0303ac2.jpg](https://github.com/user-attachments/assets/45e4011a-78f4-4848-982f-fee8223dc2f2)

**Comment by ux-git** [comment]
Hi @crldv, you can click on the 00:00 time for example to add hours:minutes in a similar way.

**Comment by crldv** [comment]
Yes it works and when adding minutes it glitches. We can consider this numeric keyboard with a colon as separator for hours and minutes instead of alphanumeric keyboard or normal keyboard that pops up and then types even letters in the input area
![Screenshot_2024-12-07-18-32-21-59_d7df185609163aa0123e4051a0303ac2.jpg](https://github.com/user-attachments/assets/927f9cde-21e5-4544-8941-dafab209ea32)

**Comment by ux-git** [comment]
@crldv could you please demonstrate how exactly it glitches?

**Comment by crldv** [comment]
Here's a screen record of the glitch when adding time with minutes 😅
https://github.com/user-attachments/assets/5413abdd-2b3a-42dd-948d-aaee047ff3f1

**Comment by ux-git** [comment]
Hmm, that's weird behavior. @rhahao do you have any idea why is it so?

The idea with a virtual keyboard is well suitable for mobile, but on desktop it will be complicated to click with a mouse on each digit on the screen instead normal keyboard.

Also, @rhahao could the keyboard type for those time-only fields be set as the "PIN keyboard" on a smartphone, like the one which has only the digits.

But we can't fix this, we can consider adding the "Clock" button, to enter the time more flexibly and in more visual way.

**Comment by rhahao** [comment]
Thank you @crldv and @ux-git. I’ll check this.
