### ISSUE TITLE
[FIX] Assigning parts in Apply to Ministry

### ISSUE THREAD

**Issue by crldv** [sws2apps/organized-app#3176]
**Describe the bug**
1. Single input box when assigning meeting parts in this field
![Screenshot_2024-12-09-19-51-33-31_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/user-attachments/assets/be12e2f8-0f35-471e-a4d9-1211e8404ecf)

2. Only brothers can be assigned in apply to ministry section
![Screenshot_2024-12-09-19-52-33-41_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/user-attachments/assets/29650d8e-319b-484e-ab7d-83475083b86d)

**Expected behavior**
1. There might be 2 input boxes, for the student and assistant.
2. Option to assign sisters in this section

**Smartphone (please complete the following information):**
 - Device: realme 8 Pro
 - OS: realme UI 4.0, Android 13
 - Browser: Kiwi Browser
 - Version 124.0.6327.4

**Comment by rhahao** [comment]
@crldv: Thanks for this report. Can you please check in this [preview url](https://deploy-preview-3178--staging-organized.netlify.app/) if this issue is fixed now?

**Comment by crldv** [comment]
@rhahao it's fix now. Thank you very much!

**Comment by crldv** [comment]
@rhahao I also noticed after exporting the schedule in tagalog, labels for the student and assistant are missing. This might cause confusion for some, what do you think?
![IMG_20241210_081800.jpg](https://github.com/user-attachments/assets/d8939c43-0300-441e-81ba-b58bf457727d)

**Comment by rhahao** [comment]
@ux-git: any comments on the comments above?

**Comment by ux-git** [comment]
@rhahao @crldv the first person is always the main student. Is there any case when this might be different?

**Comment by crldv** [comment]
@ux-git nothing much I think. Congregations that switch from S-140 layout to the standard layout that Organized had will get used to this schedule eventually
