### ISSUE TITLE
[FIX] Student assignments in APPLY YOURSELF TO THE FIELD MINISTRY parts

### ISSUE THREAD

**Issue by wikmanipoiss** [sws2apps/organized-app#3177]
**Describe the bug**
In Estonian language there is no possibility to assign students for Apply yourself to the field ministry parts

**To Reproduce**
1. Select language 'eesti'
2. Click on 'Nädalasisene koosolek'
3. Select for example 'Detsember 9'
4. See bug Apply yourself to the field ministry parts

**Expected behavior**
In English language there are all boxes visible from which to select student
![image](https://github.com/user-attachments/assets/25be86f7-b816-408d-b678-f129980f5467)

In Estonian language there is a problem
![image](https://github.com/user-attachments/assets/74a678b2-e78d-4f6f-a9ab-086947319f19)

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Chrome Version 131.0.6778.109 (Official Build) (64-bit)
 - Version 23H2

**Smartphone (please complete the following information):**
 - Device: Samsung S21 Ultra
 - OS: Android
 - Browser Chrome
 - Version 14

**Additional context**

**Comment by rhahao** [comment]
Hello @wikmanipoiss, thanks for reporting this issue. To solve this can you please make the following update on Crowdin? (The translations of the old terms used in Apply for Field Ministry overlap with the current one, even though you seems to use different ones back then. I put them below but you can double check it for accuracy):

[Initial Call ](https://crowdin.com/editor/organized/2024/en-et?view=comfortable#43622) -> Esmavestlus
[Initial Call Video](https://crowdin.com/editor/organized/2024/en-et?view=comfortable#43682) -> Esmavestluse video
[Return Visit](https://crowdin.com/editor/organized/2024/en-et?view=comfortable#43624) -> Korduskülastus
[Return Visit Video](https://crowdin.com/editor/organized/2024/en-et?view=comfortable#43684) -> Korduskülastuse video

Thanks.

**Comment by wikmanipoiss** [comment]
Hello @rhahao 
So to understand right:
Initial Call -> Starting a Conversation and so on?

**Comment by rhahao** [comment]
@wikmanipoiss: these are for the old terms, namely from the meeting workbook pre-2024. We just have them here for history purposes. For 2024 and onward, we use the Starting a Conversation term which you already translated correctly.

**Comment by wikmanipoiss** [comment]
thank you for clarification, it seems that i have translated these not correctly. Now is fixed with right terms.

**Comment by rhahao** [comment]
Thanks. They will be included with the next release.

**Comment by ux-git** [comment]
And such old strings will be marked with more context from now on: 

<img width="670" alt="Screenshot 2024-12-09 at 19 37 35" src="https://github.com/user-attachments/assets/9cb56edf-b169-4599-a136-bedc4eeb9653">
