### ISSUE TITLE
[FIX] Login layout bug

### ISSUE THREAD

**Issue by mrtavor** [sws2apps/organized-app#3184]
**Describe the bug**
Problem logging in as a baptized brother: when I am on the page where I need to enter a password to join the congregation, I refresh the page, and now instead of two functions on one page, I see the congregation registration.

**To Reproduce**
1. Register as a baptized brother.
2. Wait to be added to the congregation.
3. Access the page where you need to enter the congregation password.
4. Refresh this page.

**Screenshots**
I apologize, but I couldn’t take a screenshot of the page I described above. Whenever I tried to capture a screenshot, it always appeared black, just like the video.
I used an old screenshot where everything is visible except for the part with the code input (which I crossed out).

![IMG_20241210_083053_051.jpg](https://github.com/user-attachments/assets/56eae081-4f9a-43cf-b4c5-b694b2a022f4)

**Smartphone (please complete the following information):**
 - Device: CMF Phone 1
 - OS: Nothing OS 2.6
 - Browser PWA or Chrome
 - Version 3.3.0

**Additional context**
-

**Comment by mrtavor** [comment]
I took a photo using another phone.

![IMG_20241210_090751_646.jpg](https://github.com/user-attachments/assets/26bfb7ae-b269-4f68-a131-5c44117f3783)

**Comment by rhahao** [comment]
@mrtavor: I’ve tried to duplicate this using the steps you describe above but unfortunately I am unable to see the issue reported. Can you please try once again and let me know the result? Thanks.

**Comment by mrtavor** [comment]
Okay @rhahao , I'll try to catch it from another phone now

**Comment by mrtavor** [comment]
I skipped the part in the video where I logged into my Google account because I opened a new incognito tab, and I had to fully enter all the login details there. 
Here you are:
https://github.com/user-attachments/assets/45c47d3b-70b9-4c04-a621-674c8defe951

**Comment by rhahao** [comment]
Ok thanks. I will double check it again.

**Comment by rhahao** [comment]
@mrtavor: A fix will be deployed with the next release to address this issue. Thank you.
