### ISSUE TITLE
Error disqualifying a person

### ISSUE THREAD

**Issue by joaochris** [sws2apps/organized-app#3230]
### Describe the bug:

When pressing the disqualify button, nothing happens. An error appears in the console. And also if you close it, it appears as disqualified, however, it still appears in the designation list.

Also, the modal title is in English.

### Screenshots

![Screenshot_2024-12-15-18-30-53-348_com kiwibrowser browser](https://github.com/user-attachments/assets/24607906-b944-4587-8d7a-bceaeb6905b2)
![Screenshot_2024-12-15-18-30-43-562_com kiwibrowser browser](https://github.com/user-attachments/assets/d1ddda3d-00c1-4819-9d55-57254660eae1)

### Which platform can you reproduce the bug on?

Desktop

### Your operating system:

Windows

### App version:

Latest version

**Comment by rhahao** [comment]
@joaochris: I believe this should now be fixed. 😊 Can you please confirm?

**Comment by joaochris** [comment]
> @joaochris: I believe this should now be fixed. 😊 Can you please confirm?

Yes, it has been fixed. One person was already disqualified and was still showing up in the designation list, so I qualified and disqualified him again and it worked.
