### ISSUE TITLE
[FIX] Midweek meeting schedule has extra day on it

### ISSUE THREAD

**Issue by wikmanipoiss** [sws2apps/organized-app#3236]
### Describe the bug:

In midweek meeting scheduling there is an extra day that is placed before actual starting week of the month. 
February is for example - how it looks in the app and how it looks when I saved a pdf.

### Steps to reproduce the issue:

1. Select midweek meeting
2. Select year - 2025
3. Select month - February

### Expected behavior:

Expected is not to have this extra day in the list of weeks

### Screenshots

![image](https://github.com/user-attachments/assets/157a8f37-2271-4192-b2a2-39f86b462e3a)
![image](https://github.com/user-attachments/assets/02154dfc-00f8-497c-b6e3-69a6a93634fa)

### Which platform can you reproduce the bug on?

All platforms

### Your operating system:

Windows

### App version:

3.4.1

**Comment by rhahao** [comment]
@wikmanipoiss: Thanks for this report! Can you please verify if you still see the odd week after updating to the latest version (3.4.2)?

**Comment by wikmanipoiss** [comment]
@rhahao I can verify that this odd week is no more there. Thank you :)
