### ISSUE TITLE
Assigning parts in Apply to Ministry (old bug)

### ISSUE THREAD

**Issue by crldv** [sws2apps/organized-app#3250]
### Describe the bug:

Encountered issues experienced before after the update.
Link of the bug before update: 
[https://github.com/sws2apps/organized-app/issues/3176](url)

### Steps to reproduce the issue:

Assigned the parts (before v3.4.0 update) in English to avoid the bug.

In v3.4.2
Using Tagalog language:
Viewing Weekly schedules (assistant not displayed)
![Screenshot_2024-12-17-17-14-15-71_4d38fce200f96aeac5e860e739312e76](https://github.com/user-attachments/assets/8bbe1c28-664e-4b9d-ad51-2b3207f4364f)

Under Midweek Meeting (overlapped numbers)
![Screenshot_2024-12-17-17-20-21-96_4d38fce200f96aeac5e860e739312e76](https://github.com/user-attachments/assets/7cdc31b9-78d8-44e5-b42e-83929f03c5e1)

This schedule is from 1st MW of January 2024
(assistant box input not displayed, can't assign sisters)
![Screenshot_2024-12-17-17-15-07-48_4d38fce200f96aeac5e860e739312e76](https://github.com/user-attachments/assets/77b6a8b1-be7f-41fc-aca0-80030309546e)

### Which platform can you reproduce the bug on?

Mobile (installed as PWA)

### Your operating system:

Android

### App version:

Organized v3.4.2

### Additional information

Exported midweek schedule in Tagalog is fine

**Comment by rhahao** [comment]
@crldv: can you just try re-importing again the source materials from jw.org to see if that makes any difference. Just now, I tried with Tagalog in the test environment, but it works perfectly fine.

![image](https://github.com/user-attachments/assets/fdc006be-c6bd-40c1-a2bd-b71d46dfaa16)

**Comment by crldv** [comment]
Wow. It's fixed now. **Thanks! 😊**

**Comment by ux-git** [comment]
@crldv and has the 'Brother' in front of the student changed to the correct label(s) now? 

![image](https://github.com/user-attachments/assets/7f0f2391-6a38-4346-baae-28eefd690a33)

**Comment by crldv** [comment]
Yes it changed![Screenshot_2024-12-17-17-51-07-20_4d38fce200f96aeac5e860e739312e76.jpg](https://github.com/user-attachments/assets/9ca87c5f-1acf-40d2-be6a-c6697fd63465)
