### ISSUE TITLE
[FIX] S-89 is showing the date of the week and not the day of the meeting 

### ISSUE THREAD

**Issue by joaochris** [sws2apps/organized-app#3260]
### Describe the bug:

When exporting the designations to S-89, the date shows the Monday day of the week, not the day of the meeting.

### Screenshots

![IMG_20241219_053511](https://github.com/user-attachments/assets/77b030df-3883-4563-a6a4-36a332ee7642)

### Which platform can you reproduce the bug on?

Desktop

### Your operating system:

Windows

### App version:

Latest version

**Comment by ux-git** [comment]
Thanks @joaochris. That's the same issue like in #3146, respecting the "Use the exact meeting date" setting globally in UI and PDF should solve this problem. Let's see what can be done to achieve this.
