### ISSUE TITLE
[FEAT] Keep UI language in English, but meeting schedules in congregation language.

### ISSUE THREAD

**Issue by kentestaccount** [sws2apps/organized-app#3267]
### Feature description:

I would like to request a feature that allows users to maintain the user interface (UI) language in English while displaying meeting schedules in the congregation's preferred language, Iloko. This feature will enhance usability for users who prefer English for navigation but need meeting schedules in their native or congregation-specific language.

Currently, the application does not support the separation of Ul language and meeting schedule language (or any applicable template needed). Users who prefer English for the UI are forced to view meeting schedules in English as well, which can be inconvenient for those who need these schedules in their congregation's language. Translating the Ul into lloko makes using the app more difficult, as lloko isn't typically used in UX/UI, and users understand the default English better.

### Alternatives considered:

I can't use the app because schedules are in English. Iloko wasn't in the list so I volunteered to translate. I guess I can just continue translating into Iloko and use it after Organized is updated, or just use all English, including meeting templates.

**Comment by rhahao** [comment]
Hi @kentestaccount, thank you for this request. For such situation, this should be the recommended workflow:

- Once your language was added, you do not need to translate all texts in Crowdin. By default, english texts will be used. We can always remove the pre-translated texts and revert them back to english. In the future if you want to add your own translations or use translations from another language, you can get and enter these in Crowdin, and they will replace the english texts.
- Find only the texts that are used for meeting schedules and translate them in your language.

Thank you.

**Comment by kentestaccount** [comment]
Great! I already started translating, but if you can revert everything back to English, that would be fantastic! Also, if I find some UI elements that are better when translated into Iloko, can I just translate them in CrowdIn?

Lastly, when will Iloko appear in the app? I'm excited to test.

**Comment by rhahao** [comment]
> Also, if I find some UI elements that are better when translated into Iloko, can I just translate them in CrowdIn?

Yes feel free to do so.


> Lastly, when will Iloko appear in the app? I'm excited to test.

We will schedule a new release very soon and it will be included with that too.

Thanks
