### ISSUE TITLE
[Enhancement Idea] Texts Assignment history

### ISSUE THREAD

**Issue by joaochris** [sws2apps/organized-app#33]
I wish I could translate the letters A and B to make it easier to understand.

In Room I would put "Local" [PT-BR].

And in A and B, respectively:
Main hall [Salão principal]
Auxiliary Classroom 1 [Sala B]

![Sala](https://user-images.githubusercontent.com/76891864/221559738-53d62fb3-f84d-42a0-8f33-7d172fa6f29a.png)

**Comment by rhahao** [comment]
Hi @joaochris. Sure. I will add the necessary strings for them. I need to verify the form where we select a person for an assignment as well, since I could see that we may be run out of space with what we have currently.

**Comment by rhahao** [comment]
This was added and will be released with v3.
