### ISSUE TITLE
[FEAT]  Simplified login

### ISSUE THREAD

**Issue by joaochris** [sws2apps/organized-app#582]
Hello, I think the login process could be more simplified.

A screen asking just for:

Username/email:
Checkbox: Remember my username
Type your password:
Checkbox: Keep me logged in

And if necessary, add security questions.

And regarding Keep Me Logged in, there is no timeout to log in again. In other words, we would only be asked to log in again if we logged out of the account.

**Comment by rhahao** [comment]
Hello @joaochris, thanks for your comments and suggestions.

> And regarding Keep Me Logged in, there is no timeout to log in again. In other words, we would only be asked to log in again if we logged out of the account.

I will work on implementing this change. 👍

> Username/email:
> Checkbox: Remember my username
> Type your password:
> Checkbox: Keep me logged in
> 
> And if necessary, add security questions.

I think that we have is already simple since it follows the standard login mechanism of most websites. 😁 For most of users using the `oauth` provider login is quite straightforward: They just choose Google, or Yahoo, etc... and they are automatically signed in, since generally their email account remains connected on their personal device. Few additional steps are required for those choosing the Email Link Authentication. Also, MFA verification will now be only displayed if they choose to enable it.

**Comment by joaochris** [comment]
Thanks. But in my case, for example, when I log in with Google it asks for authentication. I would like to remove this.

**Comment by rhahao** [comment]
Yes, if the Google account is not yet connected to the browser you are using, it will ask you to authenticate. For now, if you do not wish to consent to this login method, only the email link authentication is available. May be in the future, we may come up with another method of authentication and we can build something new. 💡

**Comment by joaochris** [comment]
But are you referring to authentication from the Google Authenticator app?

**Comment by rhahao** [comment]
Using one of these 4 providers:

![image](https://github.com/sws2apps/cpe-sws/assets/26148770/0f30a7db-9f63-47cf-89f3-6b6cb2c56b19)

**Comment by joaochris** [comment]
That's right, when I log in with Google, I have already given authorization for the screen that appears. But an MFA verification appears and when I created my account I chose the Google Authenticator app. Is there a way to remove this second verification?

**Comment by rhahao** [comment]
Yes, we can disable it. And I am currently preparing an update to let the user disable their MFA. For now, I can disable it for your account.

**Comment by rhahao** [comment]
And also, I think the Google Authenticator app can be used without sign in. 😁 This is how I setup mine here.

**Comment by joaochris** [comment]
Great! That's what I was talking about :D. This makes logging in very simple.

**Comment by joaochris** [comment]
After that, the next step is to keep the user always connected :D

**Comment by rhahao** [comment]
@joaochris: Just to show you my Google Authenticator app with the "not connected" option:

![image](https://github.com/sws2apps/cpe-sws/assets/26148770/f5f557ea-ee9d-4394-b922-f9c918009c51)

**Comment by joaochris** [comment]
hey is everything good with you? I logged in, and it still appears to verify with Authenticator. What you showed in the print, I couldn't do, because I have other services connected to my Google account.

![image](https://github.com/sws2apps/cpe-sws/assets/76891864/ed3877db-b3c2-447e-a2ef-177c41dbed77)

**Comment by rhahao** [comment]
Hello @joaochris, all is good thanks! Hope the same for you.

> What you showed in the print, I couldn't do, because I have other services connected to my Google account.
Oh ok, then you can just use the Google Authenticator as you normally use it. I’m just showing that it can be used offline if some user want to it for the first time, and they don’t want to use an email address to sign up with that app.

I have not yet deactivated the two-factor verification for your account, and the feature to disable it by each user is yet to be completed. Do you want me to disable it on your behalf until then?

**Comment by joaochris** [comment]
> Oh ok, then you can just use the Google Authenticator as you normally use it. I’m just showing that it can be used offline if some user want to it for the first time, and they don’t want to use an email address to sign up with that app.

I understand now. :D

> I have not yet deactivated the two-factor verification for your account, and the feature to disable it by each user is yet to be completed. Do you want me to disable it on your behalf until then?

Oh, okay. Yes please!

**Comment by rhahao** [comment]
😄 The 2FA is now disabled for your account. At any time, you can re-enable it in the User Profile page. Thanks

**Comment by rhahao** [comment]
Hi @joaochris, an update to this one: a simplification has been made to the new Organized app that will be released in the future. Stay tuned! 😊
